spring:
    jpa.hibernate.ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/universidad
        username: root
        password: Davidbien1-
    hikari:
        connection-timeout: 60000
        maximum-pool-size: 5